name: ApiaWipeout
main: main.java.com.irfandumanx.apiawipeout.ApiaWipeout
authors: [irfandumanx, bertek41, oSoloTurk]
description: Special plugin for ApiaTeam 2021 Faction Setup
version: maven.version
softdepend: [HolographicDisplays]
api-version: 1.13
commands:
  wipeout:
    description: Main command